// Generated by CoffeeScript 1.7.1
(function(peer) {
  var audio;
  audio = $('#audio')[0];
  audio.volume = 0.3;
  return peer.on('progress', function() {
    audio.pause();
    audio.currentTime = 0;
    return audio.play();
  });
})(window.peer);
