// Generated by CoffeeScript 1.7.1
(function(peer) {
  var countUnsentFiles, onBeforeUnload, unsentFiles;
  countUnsentFiles = function() {
    var status;
    status = peer.status();
    return status.all - status.complete - status.error;
  };
  unsentFiles = countUnsentFiles();
  peer.on('add', function() {
    return unsentFiles++;
  });
  peer.on('remove', function() {
    return unsentFiles--;
  });
  peer.on('progress', function() {
    return unsentFiles--;
  });
  onBeforeUnload = function() {
    return "Möchtest du die Seite verlassen und die Übertragung von " + (countUnsentFiles()) + " Dateien abbrechen?";
  };
  peer.on('add', function() {
    if (unsentFiles === 1) {
      return window.onbeforeunload = onBeforeUnload;
    }
  });
  peer.on('remove', function() {
    if (unsentFiles === 0) {
      return window.onbeforeunload = null;
    }
  });
  return peer.on('progress', function() {
    if (unsentFiles === 0) {
      return window.onbeforeunload = null;
    }
  });
})(window.peer);
