// Generated by CoffeeScript 1.7.1
window.peer = new linkup.Peer();

(function(peer) {
  var body;
  body = $(document.body);
  if (location.hash.length > 1) {
    peer.connect(location.hash.slice(1));
    peer.mode = 'connect';
  } else {
    peer.listen();
    peer.mode = 'listen';
  }
  peer.on('open', function() {
    body.addClass('open');
    body.removeClass('closed');
    return body.removeClass(peer.mode);
  });
  peer.on('close', function() {
    body.addClass('closed');
    body.removeClass('open');
    return body.addClass(peer.mode);
  });
  body.addClass(peer.mode);
  return body.addClass(peer.open ? 'open' : 'closed');
})(window.peer);
