// Generated by CoffeeScript 1.7.1
(function(peer) {
  var button, drop;
  button = $('#select-button input');
  button.on('change', function(e) {
    var file, _i, _len, _ref, _results;
    _ref = e.target.files;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      _results.push(peer.send(file));
    }
    return _results;
  });
  drop = $('#select-drop');
  drop.on('dragenter', function(e) {
    return drop.addClass('hover');
  });
  drop.on('dragleave', function(e) {
    return drop.removeClass('hover');
  });
  drop.on('dragover', function(e) {
    e.preventDefault();
    return e.dataTransfer.dropEffect = 'copy';
  });
  return drop.on('drop', function(e) {
    var file, _i, _len, _ref, _results;
    e.preventDefault();
    drop.removeClass('hover');
    _ref = e.dataTransfer.files;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      _results.push(peer.send(file));
    }
    return _results;
  });
})(window.peer);
