// Generated by CoffeeScript 1.7.1
(function(peer) {
  var share;
  share = $('#share-input');
  share.attr('value', "" + location.href + "#" + peer.id);
  return share.on('click', function() {
    this.select();
    return this.setSelectionRange(0, 100);
  });
})(window.peer);
