// Generated by CoffeeScript 1.7.1
(function(peer) {
  var displayStatus, status;
  status = $('#status');
  displayStatus = function() {
    if (peer.isOpen) {
      return status.text('verbunden');
    } else {
      if (peer.mode === 'listen') {
        return status.text('auf eine Verbindung warten');
      } else {
        return status.html("mit <i>#" + peer.peer + "<i> verbinden");
      }
    }
  };
  peer.on('open', displayStatus);
  peer.on('close', displayStatus);
  return displayStatus();
})(window.peer);
