// Generated by CoffeeScript 1.7.1
(function(peer) {
  var displayTitle, originalTitle;
  originalTitle = document.title;
  displayTitle = function() {
    var parts, progress, title;
    title = [];
    if (!peer.open && peer.mode === 'listen') {
      title.push("#" + peer.id);
    }
    progress = peer.status();
    if (progress.all > 0 && peer.complete) {
      title.push('\u2713');
    }
    if (!peer.complete) {
      parts = [];
      if (progress.receive.all > 0) {
        parts.push("\u2193" + progress.receive.complete + "/" + progress.receive.all);
      }
      if (progress.send.all > 0) {
        parts.push("\u2191" + progress.send.complete + "/" + progress.send.all);
      }
      if (parts.length > 0) {
        title.push(parts.join('\u2002'));
      }
    }
    title.push('avion');
    return document.title = title.join(' \u2014 ');
  };
  peer.on('open', displayTitle);
  peer.on('close', displayTitle);
  peer.on('add', displayTitle);
  peer.on('remove', displayTitle);
  peer.on('progress', displayTitle);
  peer.on('transfer', displayTitle);
  peer.on('complete', displayTitle);
  return displayTitle();
})(window.peer);
